import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { createHash } from 'node:crypto';
import { prisma } from '@meridian/db';
import { getFileObject } from '../../../services/storage.service.js';

/**
 * Linux bash installer template. Variables substituted at request time:
 *   __SERVER_URL__   — full server base URL (no trailing slash)
 *   __TOKEN__        — raw enrollment token
 *   __PRIVACY_TIER__ — full | restricted | anonymized
 *
 * Inlined as a string so the API ships the installer in `dist/` without a
 * tsc copy-step. Edit this constant; do NOT add a separate .sh file.
 */
const INSTALLER_TEMPLATE = `#!/bin/bash
# MeridianITSM Inventory Agent — Linux installer
#
# Generated by /api/v1/agents/install.sh and served with an enrollment token
# baked in. Detects distro family, downloads the matching .deb or .rpm,
# installs the agent, writes config, and enrolls.
#
# Usage:
#   curl -sSL "https://<server>/api/v1/agents/install.sh?token=<token>" | sudo bash

set -euo pipefail

SERVER_URL="__SERVER_URL__"
TOKEN="__TOKEN__"
PRIVACY_TIER="__PRIVACY_TIER__"

CONFIG_DIR="/etc/meridian-agent"
CONFIG_FILE="\${CONFIG_DIR}/config.json"
SERVICE_NAME="meridian-agent"

if [[ \$EUID -ne 0 ]]; then
    echo "ERROR: this installer must run as root. Re-run with sudo."
    exit 1
fi

# Detect package manager
PKG_FORMAT=""
if command -v dpkg >/dev/null 2>&1 && command -v apt-get >/dev/null 2>&1; then
    PKG_FORMAT="DEB"
elif command -v rpm >/dev/null 2>&1 && (command -v dnf >/dev/null 2>&1 || command -v yum >/dev/null 2>&1 || command -v zypper >/dev/null 2>&1); then
    PKG_FORMAT="RPM"
else
    echo "ERROR: could not detect a supported package manager."
    echo "  Supported: apt (Debian/Ubuntu), dnf/yum (RHEL/Fedora/Rocky), zypper (openSUSE)."
    exit 1
fi

echo "=================================================================="
echo "  MeridianITSM Inventory Agent — Linux Installer"
echo "  Server:   \${SERVER_URL}"
echo "  Format:   \${PKG_FORMAT}"
echo "=================================================================="

TMP_DIR="\$(mktemp -d)"
trap 'rm -rf "\$TMP_DIR"' EXIT

EXT="\$(echo "\$PKG_FORMAT" | tr '[:upper:]' '[:lower:]')"
PACKAGE_PATH="\${TMP_DIR}/meridian-agent.\${EXT}"

DOWNLOAD_URL="\${SERVER_URL}/api/v1/agents/install/package?format=\${PKG_FORMAT}&token=\${TOKEN}"
echo "Downloading agent package..."
if ! curl --fail --silent --show-error --location -o "\${PACKAGE_PATH}" "\${DOWNLOAD_URL}"; then
    echo "ERROR: failed to download package from \${DOWNLOAD_URL}"
    exit 1
fi

echo "Installing package (\${PKG_FORMAT})..."
if [[ "\$PKG_FORMAT" == "DEB" ]]; then
    if ! dpkg -i "\${PACKAGE_PATH}" >/dev/null 2>&1; then
        apt-get update -qq >/dev/null
        apt-get install -y -f >/dev/null
        dpkg -i "\${PACKAGE_PATH}"
    fi
else
    rpm -U --force "\${PACKAGE_PATH}"
fi

echo "Writing configuration..."
mkdir -p "\${CONFIG_DIR}"
cat > "\${CONFIG_FILE}" <<CFG
{
  "AgentConfig": {
    "ServerUrl": "\${SERVER_URL}",
    "EnrollmentToken": "\${TOKEN}",
    "PrivacyTier": "\${PRIVACY_TIER}",
    "HeartbeatIntervalSeconds": 300,
    "InventoryIntervalSeconds": 14400,
    "LocalWebUiPort": 8787,
    "LocalQueueMaxSizeMb": 100,
    "LogLevel": "Information",
    "InstallFormat": "\${PKG_FORMAT}"
  }
}
CFG
chmod 640 "\${CONFIG_FILE}"
chown -R meridian-agent:meridian-agent "\${CONFIG_DIR}" 2>/dev/null || true

echo "Starting agent..."
systemctl daemon-reload
systemctl enable "\${SERVICE_NAME}" >/dev/null 2>&1 || true
systemctl restart "\${SERVICE_NAME}"

echo "Waiting for first heartbeat..."
for _ in 1 2 3 4 5 6 7 8 9 10 11 12; do
    if systemctl is-active --quiet "\${SERVICE_NAME}"; then
        echo ""
        echo "SUCCESS: agent installed and running."
        echo "  Service: \${SERVICE_NAME} (\$(systemctl is-active \${SERVICE_NAME}))"
        echo "  Config:  \${CONFIG_FILE}"
        echo "  Logs:    journalctl -u \${SERVICE_NAME} -f"
        echo ""
        echo "Check the Meridian dashboard for this endpoint within ~60 seconds."
        exit 0
    fi
    sleep 5
done

echo ""
echo "WARNING: service did not reach 'active' within 60s."
echo "  Diagnose: journalctl -u \${SERVICE_NAME} -n 100 --no-pager"
exit 1
`;

/**
 * Resolve a non-expired enrollment token from a query-string `token` value.
 * Returns the AgentEnrollmentToken record on success, or null after sending
 * a 401 reply on failure.
 */
async function resolveEnrollmentToken(
  request: FastifyRequest,
  reply: FastifyReply,
): Promise<{ tenantId: string } | null> {
  const query = request.query as { token?: string };
  const token = query.token?.trim();
  if (!token) {
    await reply.code(401).send({ error: 'token query parameter required' });
    return null;
  }

  const tokenHash = createHash('sha256').update(token).digest('hex');
  const now = new Date();

  const enrollmentToken = await prisma.agentEnrollmentToken.findFirst({
    where: {
      tokenHash,
      isActive: true,
      OR: [{ expiresAt: null }, { expiresAt: { gt: now } }],
    },
    select: { id: true, tenantId: true, maxEnrollments: true, enrollCount: true },
  });

  if (!enrollmentToken) {
    await reply.code(401).send({ error: 'Invalid or expired enrollment token' });
    return null;
  }

  if (
    enrollmentToken.maxEnrollments >= 0 &&
    enrollmentToken.enrollCount >= enrollmentToken.maxEnrollments
  ) {
    await reply.code(409).send({ error: 'Enrollment token max usage reached' });
    return null;
  }

  return { tenantId: enrollmentToken.tenantId };
}

/**
 * Sanitise a string for safe interpolation inside a shell variable assignment.
 * Restricts to URL-safe characters so a hostile token can't break out of the
 * variable assignment or alter shell parsing.
 */
function shellSafe(value: string): string {
  return value.replace(/[^a-zA-Z0-9._:/\-?=&%]/g, '');
}

/**
 * Bash installer + native package download for Linux endpoints.
 *
 * GET /api/v1/agents/install.sh?token=<t>          — returns rendered installer
 * GET /api/v1/agents/install/package?format=DEB|RPM&token=<t> — streams the package
 *
 * Both are public (no AgentKey auth — the agent doesn't exist yet at install
 * time). Auth is the enrollment token, the same token /api/v1/agents/enroll uses.
 */
export default async function agentInstallRoutes(app: FastifyInstance): Promise<void> {
  app.get('/api/v1/agents/install.sh', async (request, reply) => {
    const ctx = await resolveEnrollmentToken(request, reply);
    if (!ctx) return;

    const query = request.query as { token?: string; privacyTier?: string };
    const token = shellSafe(query.token ?? '');
    const privacyTier = ['full', 'restricted', 'anonymized'].includes(query.privacyTier ?? '')
      ? (query.privacyTier as string)
      : 'full';

    // Derive the public server URL the agent will call back to. Prefer the
    // PUBLIC_API_URL env (set in prod) and fall back to reconstructing from
    // the request — useful in dev where the host header is the right answer.
    const publicUrl =
      process.env.PUBLIC_API_URL?.replace(/\/+$/, '') ??
      `${request.protocol}://${request.headers.host ?? 'localhost'}`;
    const serverUrl = shellSafe(publicUrl);

    const rendered = INSTALLER_TEMPLATE
      .replace(/__SERVER_URL__/g, serverUrl)
      .replace(/__TOKEN__/g, token)
      .replace(/__PRIVACY_TIER__/g, privacyTier);

    reply.header('Content-Type', 'text/x-shellscript; charset=utf-8');
    reply.header('Cache-Control', 'no-store');
    return reply.send(rendered);
  });

  app.get('/api/v1/agents/install/package', async (request, reply) => {
    const ctx = await resolveEnrollmentToken(request, reply);
    if (!ctx) return;

    const query = request.query as { format?: string };
    const format = query.format?.toUpperCase();
    if (format !== 'DEB' && format !== 'RPM' && format !== 'TARGZ') {
      return reply.code(400).send({ error: 'format must be DEB, RPM, or TARGZ' });
    }

    const latest = await prisma.agentUpdate.findFirst({
      where: { platform: 'LINUX', format: format as 'DEB' | 'RPM' | 'TARGZ' },
      orderBy: { createdAt: 'desc' },
    });

    if (!latest?.storageKey) {
      return reply
        .code(404)
        .send({ error: `No LINUX agent package available in format ${format}. Upload one in Owner Admin.` });
    }

    const { body, contentLength, contentType } = await getFileObject(latest.storageKey);
    const filename = latest.storageKey.split('/').pop() ?? `agent-linux.${format.toLowerCase()}`;
    reply.header('Content-Type', contentType ?? 'application/octet-stream');
    if (contentLength) reply.header('Content-Length', contentLength);
    reply.header('Content-Disposition', `attachment; filename="${filename}"`);
    reply.header('Cache-Control', 'no-store');
    return reply.send(body);
  });
}
