-- ============================================================================
-- Phase 8 Wave 5 pre-flight gate: abort if any Asset has hardware data not yet
-- migrated to the CI side (CmdbCiServer extension).
-- ============================================================================
-- This DO block runs BEFORE the destructive DROP COLUMN statements so that a
-- missed backfill produces a clear "run packages/db/scripts/phase8-backfill.ts"
-- message instead of silent data loss.
--
-- Invariant (per CASR-01 / CASR-04 / D-01 CI-wins semantics): every Asset that
-- had any of the 10 hardware/OS/software/inventory columns populated must now
-- be linked to a CmdbConfigurationItem that has a CmdbCiServer extension row.
-- If the join below finds Assets with legacy data AND no srv row, the Wave 2
-- backfill was either skipped or partial — abort cleanly before DDL runs.
--
-- Phase 7 pattern analog: migrations/20260417215217_phase7_ci_ref_notnull/
-- migration.sql lines 1-60 (two DO blocks, RAISE EXCEPTION with actionable
-- message, Postgres auto-rollback on exception).

DO $$
DECLARE
  unmigrated_count INT;
BEGIN
  SELECT COUNT(*) INTO unmigrated_count
    FROM "assets" a
    LEFT JOIN "cmdb_configuration_items" ci ON ci."assetId" = a.id
    LEFT JOIN "cmdb_ci_servers" srv ON srv."ciId" = ci.id
   WHERE (a.hostname IS NOT NULL
          OR a."operatingSystem" IS NOT NULL
          OR a."cpuCores" IS NOT NULL
          OR a."ramGb" IS NOT NULL
          OR a."softwareInventory" IS NOT NULL)
     AND srv."ciId" IS NULL;
  IF unmigrated_count > 0 THEN
    RAISE EXCEPTION 'Phase 8 backfill incomplete: % Assets still have hardware data without a corresponding CmdbCiServer extension. Run packages/db/scripts/phase8-backfill.ts before applying this migration.', unmigrated_count;
  END IF;
END $$;

-- ============================================================================
-- Generated by Prisma below this line
-- ============================================================================
-- Phase 8 Wave 5 destructive DDL: drop the 10 Asset hardware/OS/software/
-- inventory columns. Post-apply, CmdbCiServer + CmdbSoftwareInstalled own the
-- technical profile, and Asset is a financial/ownership shell.
--
-- Per D-02 (clean drop, no _legacy column), rollback requires restoring from
-- backup. The cmdb_migration_audit table preserves Wave 2 overwritten values
-- for forensic recovery (per CONTEXT.md D-01).

ALTER TABLE "assets" DROP COLUMN "hostname",
                     DROP COLUMN "operatingSystem",
                     DROP COLUMN "osVersion",
                     DROP COLUMN "cpuModel",
                     DROP COLUMN "cpuCores",
                     DROP COLUMN "ramGb",
                     DROP COLUMN "disks",
                     DROP COLUMN "networkInterfaces",
                     DROP COLUMN "softwareInventory",
                     DROP COLUMN "lastInventoryAt";
