-- ============================================================================
-- Phase 7 pre-flight gate: abort with an actionable error if backfill incomplete
-- ============================================================================
-- This block runs BEFORE the SET NOT NULL statements so a missed backfill
-- produces a clear "run packages/db/scripts/phase7-backfill.ts" message instead
-- of a cryptic Prisma constraint violation.
--
-- The gate is tenant-agnostic (global COUNT over all tenants) because Postgres
-- enforces NOT NULL at the column level — a single null row in ANY tenant
-- fails the migration. This matches the phase7-verify.ts per-tenant report.

DO $$
DECLARE
  null_class_count int;
  null_lifecycle_count int;
  null_op_count int;
  null_env_count int;
  null_rel_count int;
BEGIN
  SELECT COUNT(*) INTO null_class_count
    FROM "cmdb_configuration_items" WHERE "classId" IS NULL;
  SELECT COUNT(*) INTO null_lifecycle_count
    FROM "cmdb_configuration_items" WHERE "lifecycleStatusId" IS NULL;
  SELECT COUNT(*) INTO null_op_count
    FROM "cmdb_configuration_items" WHERE "operationalStatusId" IS NULL;
  SELECT COUNT(*) INTO null_env_count
    FROM "cmdb_configuration_items" WHERE "environmentId" IS NULL;
  SELECT COUNT(*) INTO null_rel_count
    FROM "cmdb_relationships" WHERE "relationshipTypeId" IS NULL;

  IF null_class_count > 0 OR null_lifecycle_count > 0 OR null_op_count > 0
     OR null_env_count > 0 OR null_rel_count > 0 THEN
    RAISE EXCEPTION 'Phase 7 backfill incomplete: classId=%, lifecycleStatusId=%, operationalStatusId=%, environmentId=%, relationshipTypeId=% rows still null. Run packages/db/scripts/phase7-backfill.ts before applying this migration.',
                    null_class_count, null_lifecycle_count, null_op_count, null_env_count, null_rel_count;
  END IF;
END $$;

-- ============================================================================
-- Phase 7 pre-flight gate: defense-in-depth duplicate detection
-- ============================================================================
-- Aborts if any (sourceId, targetId, relationshipTypeId) compound duplicates
-- exist. Plan 03's phase7-backfill.ts already catches this at backfill time
-- (HOSTS + VIRTUALIZES both collapse to 'hosted_on'), but a second check here
-- is cheap and protects against a partial-backfill + unique-index race.

DO $$
DECLARE
  dup_count INT;
BEGIN
  SELECT COUNT(*) INTO dup_count FROM (
    SELECT "sourceId", "targetId", "relationshipTypeId", COUNT(*)
      FROM "cmdb_relationships"
     WHERE "relationshipTypeId" IS NOT NULL
     GROUP BY 1, 2, 3
    HAVING COUNT(*) > 1
  ) d;
  IF dup_count > 0 THEN
    RAISE EXCEPTION 'Phase 7 migration aborted: % duplicate (sourceId, targetId, relationshipTypeId) compound groups exist. Resolve duplicates (e.g., HOSTS + VIRTUALIZES collisions) before retrying.', dup_count;
  END IF;
END $$;

-- ============================================================================
-- Generated by Prisma below this line
-- ============================================================================

-- DropForeignKey
ALTER TABLE "cmdb_configuration_items" DROP CONSTRAINT "cmdb_configuration_items_classId_fkey";

-- DropForeignKey
ALTER TABLE "cmdb_configuration_items" DROP CONSTRAINT "cmdb_configuration_items_lifecycleStatusId_fkey";

-- DropForeignKey
ALTER TABLE "cmdb_configuration_items" DROP CONSTRAINT "cmdb_configuration_items_operationalStatusId_fkey";

-- DropForeignKey
ALTER TABLE "cmdb_configuration_items" DROP CONSTRAINT "cmdb_configuration_items_environmentId_fkey";

-- DropForeignKey
ALTER TABLE "cmdb_relationships" DROP CONSTRAINT "cmdb_relationships_relationshipTypeId_fkey";

-- DropIndex
DROP INDEX "cmdb_relationships_sourceId_targetId_relationshipType_key";

-- AlterTable
ALTER TABLE "cmdb_configuration_items" ALTER COLUMN "classId" SET NOT NULL,
ALTER COLUMN "lifecycleStatusId" SET NOT NULL,
ALTER COLUMN "operationalStatusId" SET NOT NULL,
ALTER COLUMN "environmentId" SET NOT NULL;

-- AlterTable
ALTER TABLE "cmdb_relationships" ALTER COLUMN "relationshipTypeId" SET NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "cmdb_relationships_sourceId_targetId_relationshipTypeId_key" ON "cmdb_relationships"("sourceId", "targetId", "relationshipTypeId");

-- AddForeignKey
ALTER TABLE "cmdb_configuration_items" ADD CONSTRAINT "cmdb_configuration_items_classId_fkey" FOREIGN KEY ("classId") REFERENCES "cmdb_ci_classes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cmdb_configuration_items" ADD CONSTRAINT "cmdb_configuration_items_lifecycleStatusId_fkey" FOREIGN KEY ("lifecycleStatusId") REFERENCES "cmdb_statuses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cmdb_configuration_items" ADD CONSTRAINT "cmdb_configuration_items_operationalStatusId_fkey" FOREIGN KEY ("operationalStatusId") REFERENCES "cmdb_statuses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cmdb_configuration_items" ADD CONSTRAINT "cmdb_configuration_items_environmentId_fkey" FOREIGN KEY ("environmentId") REFERENCES "cmdb_environments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cmdb_relationships" ADD CONSTRAINT "cmdb_relationships_relationshipTypeId_fkey" FOREIGN KEY ("relationshipTypeId") REFERENCES "cmdb_relationship_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
